import{a as S,S as v,i as n}from"./assets/vendor-mdVVRe9K.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();const w="46490288-24919c30ba7303f136305d546",$="https://pixabay.com/api/";async function m(r,o=1,l=15){const i=new URLSearchParams({key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:l}),e=`${$}?${i}`;try{return(await S.get(e)).data}catch(t){throw console.error("Error fetching data from Pixabay API:",t),t}}let p;function g(r){return r.map(({webformatURL:o,largeImageURL:l,tags:i,likes:e,views:t,comments:c,downloads:P})=>`
        <li class='gallery-item'>
          <a class="gallery-link" href="${l}">
            <img class="gallery-image" src="${o}" alt="${i}" width='358' height='200'/>
          </a>
          <ul class='img-info'>
            <li><p>Likes</p><p>${e}</p></li>
            <li><p>Views</p><p>${t}</p></li>
            <li><p>Comments</p><p>${c}</p></li>
            <li><p>Downloads</p><p>${P}</p></li>
          </ul>
        </li>`).join("")}function A(){p=new v(".gallery-link",{captionDelay:250,captionsData:"alt"})}function y(){p&&p.refresh()}const f=document.querySelector(".gallery"),d=document.querySelector(".loader"),s=document.querySelector(".load-more-btn");let a=1,u="";const h=15;A();const R=document.querySelector(".form");R.addEventListener("submit",q);s.addEventListener("click",M);function q(r){if(r.preventDefault(),u=r.currentTarget.elements.search.value.trim(),u===""){n.error({message:"Please enter a search term.",position:"topRight"});return}f.innerHTML="",a=1,s.classList.add("hidden"),L(),H()}function H(){m(u,a,h).then(r=>{if(r.totalHits===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f.insertAdjacentHTML("beforeend",g(r.hits)),y(),r.totalHits>a*h?s.classList.remove("hidden"):(s.classList.add("hidden"),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}).catch(r=>{console.error("Fetch error:",r),n.error({message:"An error occurred. Please try again later.",position:"topRight"})}).finally(()=>{b()})}function M(){a+=1,s.classList.add("hidden"),L(),m(u,a,h).then(r=>{f.insertAdjacentHTML("beforeend",g(r.hits)),y(),r.totalHits>a*h?s.classList.remove("hidden"):(s.classList.add("hidden"),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}).catch(r=>{console.error("Fetch error:",r),n.error({message:"An error occurred. Please try again later.",position:"topRight"})}).finally(()=>{b()})}function L(){console.log("Showing loader..."),d.style.display="block",d.style.visibility="visible",d.style.opacity="1",d.textContent="Loading..."}function b(){console.log("Hiding loader..."),setTimeout(()=>{d.style.display="none"},300)}
//# sourceMappingURL=index.js.map
